# Classification GMM Parameters
N_COMPONENTS_PER_CLASS: 0-2, 1-2, 2-3, 3-2, 4-2, 5-3, 6-4
N_ITER: 5

# Radiodensity HU ranges of some brain regions
BACKGROUND: 0-1
CEREBROSPINAL_FLUID: 0-6
STROKE_ISCHEMIC: 6-22
WHITE_MATTER: 23-35
GRAY_MATTER: 35-41
STROKE_HEMORRHAGIC: 50-81
CALCIFICATION: 130-250